version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bookdb
    networks:
      - app-network

  backend:
    build: ./Book-Management-System
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: book-management-frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
